/**
 * Assegna l'icona a un prodotto dal suo nome. Le regole sono ordinate: vince la
 * prima che combacia, cosi' "latte di mandorla" prende l'icona vegetale e non
 * quella del latte. Se nessuna combacia si ricade sull'icona di categoria.
 */
const RULES: [RegExp, string][] = [
  // Preparati che contengono il nome dell'ingrediente fresco: vanno prima,
  // altrimenti "passata di pomodoro" finisce in ortofrutta.
  [/\bpassata|pelati|polpa di pomodoro|sugo|rag[uù]\b|concentrato di pomodoro/i, "tomato-sauce"],
  [/\btonno\b|sgombr|alici|acciugh|sardin/i, "tuna-can"],

  [/\b(latte di soia|latte di mandorla|bevanda vegetale|latte di riso|latte di avena)\b/i, "soy-milk"],
  [/\b(tofu|seitan|tempeh)\b/i, "tofu"],
  [/\bhummus\b/i, "hummus"],
  [/\bburger veg|veg burger|hamburger vegetale\b/i, "veg-burger"],

  [/\bcarot/i, "carrot"],
  [/\bpatat[ae]\b|\bpatate\b/i, "potato"],
  [/\bcipoll/i, "onion"],
  [/\bpomodor/i, "tomato"],
  [/\b(insalat|lattug|rucola|spinac|valerian|songino)/i, "salad"],
  [/\bzucchin/i, "zucchini"],
  [/\bmelanzan/i, "eggplant"],
  [/\bpeperon/i, "pepper"],
  [/\bfungh|champignon|porcin/i, "mushroom"],
  [/\bbroccol|cavolfior|cavol/i, "broccoli"],
  [/\bfinocch/i, "fennel"],
  [/\bsedan/i, "celery"],
  [/\baglio\b/i, "garlic"],
  [/\blimon/i, "lemon"],
  [/\barance|arancia|clementin|mandarin/i, "orange"],
  [/\bmel[ae]\b|\bmele\b/i, "apple"],
  [/\bbanan/i, "banana"],
  [/\bper[ae]\b/i, "pear"],
  [/\buva\b|\buvetta\b/i, "grapes"],
  [/\bfragol/i, "strawberry"],
  [/\bkiwi\b/i, "kiwi"],
  [/\bavocado\b/i, "avocado"],

  [/\bbaguette|filon/i, "baguette"],
  [/\bcornett|brioche|croissant/i, "croissant"],
  [/\bfocacc/i, "focaccia"],
  [/\bgrissin/i, "breadstick"],
  [/\bfette biscottate|pancarr|pane in cassetta|toast/i, "toast"],
  [/\bcracker|tarall|salatin/i, "cracker"],
  [/\bpiadin|tortilla|wrap\b/i, "flatbread"],
  [/\bpane\b|\bpagnott|michett|rosett/i, "bread"],

  [/\bpoll[oa]\b|\btacchin/i, "chicken"],
  [/\bmanzo|vitell|bovin|bistecc|hamburger|macinat/i, "beef"],
  [/\bmaial|suin|braciol|lonza\b/i, "pork"],
  [/\bsalsicc|wurstel|salamell/i, "sausage"],
  [/\bsalmon/i, "salmon"],
  [/\bgamber|mazzancoll/i, "shrimp"],
  [/\bcozz|vongol|frutti di mare/i, "mussel"],
  [/\bbastoncini di pesce/i, "fish-stick"],
  [/\bpesce|orata|branzin|merluzz|platess|tonno fresco|sogliol|calamar/i, "fish"],

  [/\bpanna\b|\bbesciamell/i, "cream"],
  [/\bburro\b/i, "butter"],
  [/\buov[ao]\b/i, "egg"],
  [/\byogurt|yoghurt|skyr\b/i, "yogurt"],
  [/\bmozzarell|burrat|fiordilatt/i, "mozzarella"],
  [/\bparmigian|grana\b|pecorin/i, "parmesan"],
  [/\bprosciutt|speck|bresaol|coppa\b/i, "ham"],
  [/\bsalame|salamin|mortadell|soppress/i, "salami"],
  [/\bpancett|guancial|bacon\b/i, "bacon"],
  [/\bformagg|stracchin|gorgonzol|ricott|mascarpon|sottilett|cheddar|philadelphia/i, "cheese"],
  [/\blatte\b/i, "milk"],

  [/\bspaghett|vermicell|linguin|bucatin/i, "spaghetti"],
  [/\bris[oi]\b|basmati|carnaroli|arborio|couscous|cous cous|quinoa|orzo perlato|farro\b/i, "rice"],
  [/\bfarin[ae]\b|lievit/i, "flour"],
  [/\bpasta\b|penne|fusill|rigaton|farfall|lasagn|tortellin|ravioli|gnocch|maccheron/i, "pasta"],

  [/\bpesto\b/i, "pesto"],
  [/\bolio extraverg|olio d'oliva|olio di oliva/i, "olive-oil"],
  [/\bolio\b/i, "oil"],
  [/\boliv[ae]\b/i, "olive"],
  [/\bmarmellat|confettur|crema spalmabile|nocciolata|nutella/i, "jam"],
  [/\bmiele\b/i, "honey"],
  [/\bacet[oi]\b/i, "vinegar"],
  [/\bmaionese|ketchup|senape|salsa\b|soia\b/i, "sauce"],
  [/\bfagiol|cec[i]\b|lentic|piselli\b|legum/i, "beans"],
  [/\bmais\b/i, "corn"],
  [/\bsott'?ol|sottacet|carciofin|giardinier/i, "jar"],

  [/\bmuesli|granola|avena|fiocchi\b/i, "muesli"],
  [/\bcereali|corn flakes|frosties/i, "cereal"],
  [/\bbiscott|frollin|wafer|pavesin/i, "biscuit"],
  [/\bmerendin|plumcake|brioss|snack dolce/i, "snack-cake"],
  [/\bcioccolat|tavolett/i, "chocolate"],
  [/\bbarrett/i, "bar"],
  [/\bcaramell|gommos|liquiriz/i, "candy"],
  [/\bbudin|dessert\b|mousse/i, "pudding"],
  [/\btort[ae]\b|panetton|pandor|crostat/i, "cake"],
  [/\bcacao\b/i, "cocoa"],
  [/\bcaff[eè]|cialde|capsule|orzo solubile/i, "coffee"],
  [/\bt[eè]\b|infus|camomill|tisan/i, "tea"],
  [/\bzucchero\b|dolcificant/i, "sugar"],
  [/\bpatatin|chips\b/i, "chips"],
  [/\barachid|pistacch|noccioline/i, "peanut"],
  [/\bpopcorn\b/i, "popcorn"],
  [/\bnoc[ie]\b|mandorl|nocciol[ae]\b|anacard/i, "nut"],
  [/\buvett|albicocche secche|datter|prugne secche|fichi secchi/i, "raisin"],
  [/\bsemi di\b/i, "seed"],
  [/\bsale\b/i, "salt"],
  [/\bpepe\b|paprika|curry|cannella|noce moscata|curcuma|peperoncin/i, "pepper-spice"],
  [/\borigan|basilic|rosmarin|salvia|timo\b|prezzemol|erbe\b/i, "herb"],

  [/\bacqua\b/i, "water"],
  [/\bsucco|spremut|nettare/i, "juice"],
  [/\bcola\b|aranciata|gassos|chinotto|t[eè] freddo|bibita|energy/i, "soda"],
  [/\bbirra\b|birre\b/i, "beer"],
  [/\bvino\b|prosecc|lambrusc|spumant|champagne|rosso\b|bianco\b|spritz/i, "wine"],

  [/\bgelat[oi]\b|cornetti gelato|ghiacciol/i, "ice-cream"],
  [/\bpizza\b/i, "pizza"],
  [/\bpatatine fritte|fries\b/i, "fries"],
  [/\bsurgelat|minestron/i, "frozen-peas"],

  [/\bdetersivo|ammorbident|candeggin|lavatrice/i, "detergent"],
  [/\bpiatti\b|lavastovigl/i, "dish-soap"],
  [/\bsgrassator|anticalcar|spray\b/i, "spray"],
  [/\bspugn/i, "sponge"],
  [/\bsacch(i|etti) (per la )?spazzatur|sacchi immondizia/i, "trash-bag"],
  [/\bcarta igienic/i, "toilet-paper"],
  [/\brotolon|carta cucina|asciugatutto/i, "paper-towel"],
  [/\bfazzolett|tovagliol|veline\b/i, "tissue"],
  [/\bpellicol|alluminio|carta forno/i, "wrap"],
  [/\bshampoo|balsamo\b/i, "shampoo"],
  [/\bdentifric/i, "toothpaste"],
  [/\bspazzolin/i, "toothbrush"],
  [/\bdeodorant/i, "deodorant"],
  [/\brasoi|rasoio|lamett/i, "razor"],
  [/\bcotone|cotton fioc|ovatta|dischetti/i, "cotton"],
  [/\bbagnoschium|sapone|docciaschium/i, "soap"],
  [/\bpannolin/i, "diaper"],
  [/\bsalviett/i, "wipes"],
  [/\bomogeneizzat|biscotti per l'infanzia|pappa\b|latte in polvere/i, "baby-food"],
  [/\bcane\b|cani\b/i, "dog-food"],
  [/\bgatt/i, "cat-food"],
  [/\blettier/i, "litter"],
];

export function iconForProduct(name: string, extra = ""): string | undefined {
  const text = `${name} ${extra}`;
  for (const [pattern, icon] of RULES) {
    if (pattern.test(text)) return icon;
  }
  return undefined;
}
